### ISSUE TITLE
Notify about auth key

### ISSUE THREAD

**Issue by gdmn** [coder/wush#22] opened 2024-09-12 14:31 UTC
It would be beneficial if the `serve` command could execute an external script, passing the randomized auth key as an argument. Alternatively, it could write the auth key to a user-specified file.

Use case:
- Run wush as a systemd service.
- Send a notification containing the auth key to ntfy.sh (or any other service, communicator, webhook, etc.).
- Connect from another PC.

**Comment by gdmn** [comment] 2024-09-12 14:33
it probably is duplicate of #16

**Comment by ammario** [comment] 2024-09-12 18:45
Definitely a duplicate of #16 but good feature request

**Closed by ammario** 2024-09-12 18:45 UTC
Labels: enhancement
